### ISSUE TITLE
Scheduler to Release Room 

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/ihram-front-desk#14]
Untuk room yang tidak check in melewati jam 6 malam

--Detail soon

**Comment by sumayyah42** [comment]
error found
![auto_release_reservation](https://user-images.githubusercontent.com/25950059/65657736-ee348100-e04e-11e9-9f85-292497391184.JPG)

reservasi yg belum check in dan sudah lewat dari tanggal expected arrival belum ter-cancel

**Comment by anra54** [comment]
fix sudah dipush di f03653ac98dbf8dcad56c597e106f50060b77305

**Comment by sumayyah42** [comment]
@anra54 Ketika auto release room berjalan, ubah juga status reservation detail pada tabel Room Booking dari Booked menjadi Canceled supaya pada halaman Room Availibility Page kamar tersebut tidak tercatat sebagai room sold dan bisa muncul di pencarian kamar reservasi
