### ISSUE TITLE
Billling From Sales Invoice Without Tax

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/ihram-front-desk#32]
Ketika terdapat sales invoice guest yang tidak menggunakan tax, akan muncul error ketika mengklik tombol billing yang membuat billing tidak bisa dilihat
![image](https://user-images.githubusercontent.com/25950059/66031430-95248b80-e52d-11e9-8861-f4aa7c928417.png)

**Comment by anra54** [comment]
fix pushed at 5694c6b187e59ccefe115afc4c3e1617a0e569fe

**Comment by sumayyah42** [comment]
Solved

**Comment by anra54** [comment]
kalo udah solved sekalian diclose issuenya dong aw aw
