### ISSUE TITLE
Initial Room Stay hasil Move Room di hari yang sama tetap kena Auto Room Charge

### ISSUE THREAD

**Issue by anra54** [purwaren/ihram-front-desk#33]
**Req:**
- room_stay awal
  - arrival: tanggal x
  - departure: tanggal y, where y > x

Move Room di hari yang sama dengan checkin mengakibatkan kondisi:
- room_stay awal
  - arrival: tanggal x
  - departure: tanggal x
- room_stay baru
  - arrival: tanggal x
  - departure: tanggal y, where y > x

**Kondisi Awal:**
Di Folio, ada dua auto room charge untuk room_stay awal dan room_stay baru. 

**Kondisi semestinya**
Semestinya hanya ada charge untuk room_stay baru

**Comment by anra54** [comment]
![3c003a12-a629-48b7-9db7-ff1ea4926ffe](https://user-images.githubusercontent.com/4516687/66116716-6970d680-e5fd-11e9-9108-20727db956ef.jpg)
 fix at 83fa4f730c408b1c1eb24b458bfe1ab8ee12d97a

**Comment by sumayyah42** [comment]
Solved
