### ISSUE TITLE
Journal Entry Auto Room Charge

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/ihram-front-desk#37]
Untuk input journal entry ketika auto room charge, akun yang di debit adalah akun DP Kamar dan akun yang di kredit adalah akun pendapatan (baik pendapatan kamar ataupun resto). Karena akun pendapatan (revenue) bertambah pada kredit dan mengurangi kewajiban pemberian jasa (liability) dari pembayaran DP dengan di debit
contoh:
Bayar DP 500,000

| Trx | Debit | Credit |
| --- | --- | --- |
| Kas FO | 500.000 |  |
| DP Kamar |  | 500.000 |

Ketika Auto Room Charge

| Trx | Debit | Credit |
| --- | --- | --- |
| DP Kamar | 500.000 |  |
| Pendapatan Kamar |  | 500.000 |

![image](https://user-images.githubusercontent.com/25950059/66381982-85e98600-e9e4-11e9-93e1-0b87f643d145.png)
Credit dan debit di atas perlu dibalik

**Comment by anra54** [comment]
@sumayyah42 

- fix u/ auto room charge di e0ce0dfd2b3d778d2c74e3a656fc6bf57d1989b2
- fix u/ special charge (early checkin / late checkout) di 9a10d62b2ae99f072d1458ed948b51ff588eff63
- fix u/ additional charge di fc4e5741744eb85b1e7635a20bf80dba7d74a3c2

kalo dicek bener jangan lupa diclose
