### ISSUE TITLE
COA Used In Backend

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/ihram-front-desk#39]
1111.003 - Front Office (manually added)
1121.0xx - Bank xx (bank account used to receive money)
1132.001 - Piutang lain-lain
1172.000 - Deposit Customer (manually added)

2121.002 - DP Kamar (manually added)

4320.001 - Pendapatan Kamar (manually added after parent 4320.000 - Pendapatan Kamar)

**Comment by anra54** [comment]
2121.002 - DP Kamar (Manually added)

**Comment by anra54** [comment]
btw kalo bikin catatan baiknya di wiki bu @sumayyah42

**Comment by sumayyah42** [comment]
siap
