### ISSUE TITLE
After-Cleaning Doctype

### ISSUE THREAD

**Issue by sumayyah42** [purwaren/ihram-front-desk#77]
Menampilkan list kamar yang sedang in house
atribut yang disimpan
- room id: read-only
- room status: read-only
- reservation id: read-only
- status: dropdown pilihan Do Not Disturb, Double Lock, Sleep Out, Clean
   - kalo yang dipilih status clean , ubah room status jadi occupied clean
- modified : timestamp-ditampilkan untuk melihat kapan pengecekan dari HK pada hari itu
- modified by: username - ditampilkan

**Comment by sumayyah42** [comment]
![image](https://user-images.githubusercontent.com/25950059/71787521-7ca3a000-304b-11ea-8805-eb0204adecec.png)
Di reservation.py masih ada yg memanggil After Cleaning doctype yg membuat error

**Comment by anra54** [comment]
fix 6c7da58be3ed62eb16519fea8faf16acc195e645
